language: php
php:
  - '7.1'

jobs:
  include:
    - stage: lint
      install: composer install -o
      script: php vendor/bin/ecs check {src,tests}
    - stage: test
      install: composer install -o
      script: php vendor/bin/phpunit
    - stage: analysis
      install: composer install -o
      script: php vendor/bin/psalm
